app {
  routes {
    # If ask takes more time than this to complete the request is failed
    ask-timeout = 10s
  }
}

akka {
  loglevel = "DEBUG"
  loglevel = ${?LOG_LEVEL}
  http.server.enable-http2 = on
  loggers = ["akka.event.slf4j.Slf4jLogger"]
}

keycloak {
#  configfile = "./src/main/resources/keycloak.json"
#  configfile = ${?KEYCLOAK_CONFIG_JSON}
  url = "http://localhost:7080/"
  url = ${?KEYCLOAK_ADMIN_URL}
  realm = "EEGFaktura"
  realm = ${?KEYCLOAK_ADMIN_REALM}
  clientId = "admin-cli"
  clientId = ${?KEYCLOAK_ADMIN_AUDIENCE}
  secret = "P85u55EUB7w6JFjQBxsHDCbdy8TXibDI"
  secret = ${?KEYCLOAK_ADMIN_SECRET}
}

keycloakAuthenticator {
  url = ${?KEYCLOAK_URL}
  realm = ${?KEYCLOAK_REALM}
  clientId = ${?KEYCLOAK_AUDIENCE}
}

akka.grpc.client {
    "register.RegisterEegService" {
      host = 127.0.0.1
      host = ${?REGISTER_SERVICE_HOST_EEG}
      port = 9092
      use-tls = false
    }
    "register.RegisterPontonService" {
      host = 127.0.0.1
      host = ${?REGISTER_SERVICE_HOST_PONTON}
      port = 9093
      use-tls = false
    }
}

# slick.pgsql.local {
#   dataSourceClass = "slick.jdbc.DatabaseUrlDataSource"
#   default {
#       driver = "slick.driver.PostgresDriver$"
#       db {
#         driver="org.postgresql.Driver"
#         url="jdbc:postgresql://localhost:6432/postgresdb"
#         user="postgresuser"
#         password="postgresPW"
#         queueSize=5000
#         connectionTimeout=30000
#         maxConnections=8
#         minConnections=2
#         numThreads=8
#       }
#   }
# }

slick.pgsql.vfeeg = {
    connectionPool = "HikariCP" //use HikariCP for our connection pool
    dataSourceClass = "org.postgresql.ds.PGSimpleDataSource" //Simple datasource with no connection pooling. The connection pool has already been specified with HikariCP.
    properties = {
        serverName = "localhost"
        serverName = ${?DATABASE_HOST}
        portNumber = "4432"
        portNumber = ${?DATABASE_PORT}
        databaseName = "postgresdb"
        databaseName = ${?DATABASE_DBNAME}
        user="postgresuser"
        user=${?DATABASE_USER}
        password="postgresPW"
        password=${?DATABASE_PASSWORD}
    }
    numThreads = 10
    queueSize=5000
    connectionTimeout=30000
    maxConnections=10
    minConnections=2
}